# packages.R — déclaration explicite pour shinyapps.io
library(shiny)
library(shinyjs)
library(DT)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyr)
library(jsonlite)
library(RSQLite)
library(DBI)
library(lubridate)
library(RColorBrewer)
library(stringi)
library(readxl)
library(readr)
library(httr)
library(digest)
library(qrcode)
# gtsummary exclu — requiert V8/juicyjuice non disponible sur shinyapps.io
